// Physics & math equation archive for the sketch board.
// Formulas use Unicode math so they render as plain canvas text —
// no LaTeX engine needed, and they stay editable after insertion.

export interface EquationPreset {
  formula: string;
  nameEn: string;
  nameHe: string;
}

export interface EquationCategory {
  key: string;
  labelEn: string;
  labelHe: string;
  equations: EquationPreset[];
}

export const EQUATION_CATEGORIES: EquationCategory[] = [
  {
    key: "mechanics",
    labelEn: "Classical Mechanics",
    labelHe: "מכניקה קלאסית",
    equations: [
      { formula: "F = ma", nameEn: "Newton's second law", nameHe: "החוק השני של ניוטון" },
      { formula: "F = dp/dt", nameEn: "Newton's second law (momentum)", nameHe: "החוק השני (תנע)" },
      { formula: "p = mv", nameEn: "Momentum", nameHe: "תנע" },
      { formula: "J = FΔt = Δp", nameEn: "Impulse", nameHe: "מתקף" },
      { formula: "v = v₀ + at", nameEn: "Velocity under constant acceleration", nameHe: "מהירות בתאוצה קבועה" },
      { formula: "x = x₀ + v₀t + ½at²", nameEn: "Position under constant acceleration", nameHe: "מיקום בתאוצה קבועה" },
      { formula: "v² = v₀² + 2aΔx", nameEn: "Velocity-displacement relation", nameHe: "קשר מהירות-העתק" },
      { formula: "W = F·d", nameEn: "Work", nameHe: "עבודה" },
      { formula: "W = ΔEₖ", nameEn: "Work-energy theorem", nameHe: "משפט עבודה-אנרגיה" },
      { formula: "P = dW/dt", nameEn: "Power", nameHe: "הספק" },
      { formula: "Eₖ = ½mv²", nameEn: "Kinetic energy", nameHe: "אנרגיה קינטית" },
      { formula: "U = mgh", nameEn: "Gravitational potential energy", nameHe: "אנרגיה פוטנציאלית כבידתית" },
      { formula: "F = -∇U", nameEn: "Force from potential", nameHe: "כוח מפוטנציאל" },
      { formula: "F = -kx", nameEn: "Hooke's law", nameHe: "חוק הוק" },
      { formula: "f = μN", nameEn: "Friction", nameHe: "חיכוך" },
      { formula: "L = Iω", nameEn: "Angular momentum", nameHe: "תנע זוויתי" },
      { formula: "τ = r × F", nameEn: "Torque", nameHe: "מומנט כוח" },
      { formula: "I = Σmᵢrᵢ²", nameEn: "Moment of inertia", nameHe: "מומנט התמד" },
      { formula: "Eₖ = ½Iω²", nameEn: "Rotational kinetic energy", nameHe: "אנרגיה קינטית סיבובית" },
      { formula: "a = v²/r", nameEn: "Centripetal acceleration", nameHe: "תאוצה צנטריפטלית" },
      { formula: "F = mv²/r", nameEn: "Centripetal force", nameHe: "כוח צנטריפטלי" },
      { formula: "x(t) = A cos(ωt + φ)", nameEn: "Simple harmonic motion", nameHe: "תנועה הרמונית פשוטה" },
      { formula: "ω = √(k/m)", nameEn: "SHM angular frequency", nameHe: "תדירות זוויתית של מתנד" },
      { formula: "T = 2π√(L/g)", nameEn: "Pendulum period", nameHe: "זמן מחזור מטוטלת" },
      { formula: "x(t) = Ae^(-γt)cos(ωt)", nameEn: "Damped oscillation", nameHe: "תנודה מרוסנת" },
    ],
  },
  {
    key: "analytical",
    labelEn: "Analytical Mechanics",
    labelHe: "מכניקה אנליטית",
    equations: [
      { formula: "L = T - V", nameEn: "Lagrangian", nameHe: "לגראנז'יאן" },
      { formula: "d/dt(∂L/∂q̇ᵢ) - ∂L/∂qᵢ = 0", nameEn: "Euler-Lagrange equations", nameHe: "משוואות אוילר-לגראנז'" },
      { formula: "d/dt(∂L/∂q̇ᵢ) - ∂L/∂qᵢ = Qᵢ", nameEn: "Euler-Lagrange (generalized forces)", nameHe: "אוילר-לגראנז' עם כוחות מוכללים" },
      { formula: "pᵢ = ∂L/∂q̇ᵢ", nameEn: "Generalized (canonical) momentum", nameHe: "תנע מוכלל (קנוני)" },
      { formula: "Qᵢ = Σⱼ Fⱼ·(∂rⱼ/∂qᵢ)", nameEn: "Generalized force", nameHe: "כוח מוכלל" },
      { formula: "∂L/∂qᵢ = 0 ⟹ pᵢ = const", nameEn: "Cyclic coordinate (conserved momentum)", nameHe: "קואורדינטה מחזורית (תנע נשמר)" },
      { formula: "S = ∫ L dt", nameEn: "Action functional", nameHe: "פונקציונל הפעולה" },
      { formula: "δS = δ∫ L dt = 0", nameEn: "Hamilton's principle (stationary action)", nameHe: "עקרון המילטון (פעולה נייחת)" },
      { formula: "Σᵢ (Fᵢ - ṗᵢ)·δrᵢ = 0", nameEn: "D'Alembert's principle", nameHe: "עקרון ד'אלמבר" },
      { formula: "L → L + dF(q,t)/dt", nameEn: "Gauge freedom of the Lagrangian", nameHe: "חופש כיול של הלגראנז'יאן" },
      { formula: "gₖ(q, t) = 0", nameEn: "Holonomic constraint", nameHe: "אילוץ הולונומי" },
      { formula: "d/dt(∂L/∂q̇ᵢ) - ∂L/∂qᵢ = Σₖ λₖ ∂gₖ/∂qᵢ", nameEn: "Lagrange multipliers (constraints)", nameHe: "כופלי לגראנז' (אילוצים)" },
      { formula: "H = Σᵢ pᵢq̇ᵢ - L", nameEn: "Hamiltonian (Legendre transform)", nameHe: "המילטוניאן (התמרת לז'נדר)" },
      { formula: "q̇ᵢ = ∂H/∂pᵢ", nameEn: "Hamilton's equation (position)", nameHe: "משוואת המילטון (מקום)" },
      { formula: "ṗᵢ = -∂H/∂qᵢ", nameEn: "Hamilton's equation (momentum)", nameHe: "משוואת המילטון (תנע)" },
      { formula: "dH/dt = ∂H/∂t", nameEn: "Time evolution of the Hamiltonian", nameHe: "התפתחות ההמילטוניאן בזמן" },
      { formula: "H = T + V", nameEn: "Hamiltonian as total energy", nameHe: "המילטוניאן כאנרגיה כוללת" },
      { formula: "{A,B} = Σᵢ(∂A/∂qᵢ ∂B/∂pᵢ - ∂A/∂pᵢ ∂B/∂qᵢ)", nameEn: "Poisson bracket", nameHe: "סוגר פואסון" },
      { formula: "dA/dt = {A, H} + ∂A/∂t", nameEn: "Evolution via Poisson bracket", nameHe: "התפתחות דרך סוגר פואסון" },
      { formula: "{qᵢ, pⱼ} = δᵢⱼ", nameEn: "Fundamental Poisson brackets", nameHe: "סוגרי פואסון יסודיים" },
      { formula: "pᵢ = ∂F₁/∂qᵢ,  Pᵢ = -∂F₁/∂Qᵢ", nameEn: "Generating function F₁(q,Q,t)", nameHe: "פונקציה יוצרת F₁(q,Q,t)" },
      { formula: "K = H + ∂F/∂t", nameEn: "New Hamiltonian (canonical transform)", nameHe: "המילטוניאן חדש (טרנספורמציה קנונית)" },
      { formula: "H(q, ∂S/∂q, t) + ∂S/∂t = 0", nameEn: "Hamilton-Jacobi equation", nameHe: "משוואת המילטון-יעקבי" },
      { formula: "S(q,α,t) = W(q,α) - Et", nameEn: "Hamilton's characteristic function", nameHe: "פונקציית המילטון האופיינית" },
      { formula: "J = Σᵢ pᵢ δqᵢ = const", nameEn: "Noether charge (conserved)", nameHe: "מטען נתר (נשמר)" },
      { formula: "∂ρ/∂t + {ρ, H} = 0", nameEn: "Liouville's equation", nameHe: "משוואת ליוביל" },
      { formula: "dρ/dt = 0", nameEn: "Liouville's theorem", nameHe: "משפט ליוביל" },
      { formula: "Jᵢ = ∮ pᵢ dqᵢ", nameEn: "Action variable", nameHe: "משתנה פעולה" },
      { formula: "νᵢ = ∂H/∂Jᵢ", nameEn: "Action-angle frequency", nameHe: "תדר במשתני פעולה-זווית" },
      { formula: "R = Σₖ pₖq̇ₖ - L", nameEn: "Routhian", nameHe: "רותיאן" },
    ],
  },
  {
    key: "gravitation",
    labelEn: "Gravitation & Cosmology",
    labelHe: "כבידה וקוסמולוגיה",
    equations: [
      { formula: "F = Gm₁m₂/r²", nameEn: "Newton's gravitation", nameHe: "חוק הכבידה של ניוטון" },
      { formula: "g = GM/r²", nameEn: "Gravitational field", nameHe: "שדה כבידה" },
      { formula: "U = -Gm₁m₂/r", nameEn: "Gravitational potential energy", nameHe: "אנרגיה פוטנציאלית כבידתית" },
      { formula: "v_esc = √(2GM/r)", nameEn: "Escape velocity", nameHe: "מהירות מילוט" },
      { formula: "T² = (4π²/GM)a³", nameEn: "Kepler's third law", nameHe: "החוק השלישי של קפלר" },
      { formula: "r_s = 2GM/c²", nameEn: "Schwarzschild radius", nameHe: "רדיוס שוורצשילד" },
      { formula: "v = H₀d", nameEn: "Hubble's law", nameHe: "חוק האבל" },
      { formula: "(ȧ/a)² = 8πGρ/3", nameEn: "Friedmann equation", nameHe: "משוואת פרידמן" },
      { formula: "S = kA c³/4Gℏ", nameEn: "Bekenstein-Hawking entropy", nameHe: "אנטרופיית בקנשטיין-הוקינג" },
    ],
  },
  {
    key: "em",
    labelEn: "Electromagnetism & Circuits",
    labelHe: "אלקטרומגנטיות ומעגלים",
    equations: [
      { formula: "∇·E = ρ/ε₀", nameEn: "Gauss's law (Maxwell I)", nameHe: "חוק גאוס (מקסוול 1)" },
      { formula: "∇·B = 0", nameEn: "No magnetic monopoles (Maxwell II)", nameHe: "אין מונופולים מגנטיים (מקסוול 2)" },
      { formula: "∇×E = -∂B/∂t", nameEn: "Faraday's law (Maxwell III)", nameHe: "חוק פאראדיי (מקסוול 3)" },
      { formula: "∇×B = μ₀J + μ₀ε₀ ∂E/∂t", nameEn: "Ampère-Maxwell law (Maxwell IV)", nameHe: "חוק אמפר-מקסוול (מקסוול 4)" },
      { formula: "F = qE + qv×B", nameEn: "Lorentz force", nameHe: "כוח לורנץ" },
      { formula: "F = kq₁q₂/r²", nameEn: "Coulomb's law", nameHe: "חוק קולון" },
      { formula: "Φ_B = ∫B·dA", nameEn: "Magnetic flux", nameHe: "שטף מגנטי" },
      { formula: "ε = -dΦ_B/dt", nameEn: "Induced EMF", nameHe: "כא\"מ מושרה" },
      { formula: "B = μ₀I/2πr", nameEn: "Field of a straight wire", nameHe: "שדה של תיל ישר" },
      { formula: "V = IR", nameEn: "Ohm's law", nameHe: "חוק אוהם" },
      { formula: "P = IV = I²R", nameEn: "Electrical power", nameHe: "הספק חשמלי" },
      { formula: "C = Q/V", nameEn: "Capacitance", nameHe: "קיבול" },
      { formula: "U = ½CV²", nameEn: "Capacitor energy", nameHe: "אנרגיית קבל" },
      { formula: "U = ½LI²", nameEn: "Inductor energy", nameHe: "אנרגיית סליל" },
      { formula: "V(t) = V₀e^(-t/RC)", nameEn: "RC discharge", nameHe: "פריקת קבל RC" },
      { formula: "f₀ = 1/2π√(LC)", nameEn: "LC resonance", nameHe: "תדר תהודה LC" },
      { formula: "Z = √(R² + (X_L - X_C)²)", nameEn: "AC impedance", nameHe: "עכבה בזרם חילופין" },
      { formula: "u = ε₀E²/2 + B²/2μ₀", nameEn: "EM energy density", nameHe: "צפיפות אנרגיית השדה" },
      { formula: "S = (E×B)/μ₀", nameEn: "Poynting vector", nameHe: "וקטור פוינטינג" },
      { formula: "c = 1/√(μ₀ε₀)", nameEn: "Speed of light from EM", nameHe: "מהירות האור מקבועי השדה" },
    ],
  },
  {
    key: "quantum",
    labelEn: "Quantum Mechanics",
    labelHe: "מכניקת הקוונטים",
    equations: [
      { formula: "E = hf = ℏω", nameEn: "Planck relation", nameHe: "יחס פלאנק" },
      { formula: "λ = h/p", nameEn: "de Broglie wavelength", nameHe: "אורך גל דה-ברויי" },
      { formula: "hf = φ + Eₖ", nameEn: "Photoelectric effect", nameHe: "האפקט הפוטואלקטרי" },
      { formula: "Eₖ = hf - φ", nameEn: "Photoelectron kinetic energy", nameHe: "אנרגיה קינטית של פוטואלקטרון" },
      { formula: "Eₖ = ℏω - φ", nameEn: "Photoelectron energy (ℏω form)", nameHe: "אנרגיית פוטואלקטרון (צורת ℏω)" },
      { formula: "Δλ = (h/mc)(1 - cosθ)", nameEn: "Compton scattering", nameHe: "פיזור קומפטון" },
      { formula: "1/λ = R(1/n₁² - 1/n₂²)", nameEn: "Rydberg formula", nameHe: "נוסחת רידברג" },
      { formula: "iℏ ∂ψ/∂t = Ĥψ", nameEn: "Schrödinger equation (time-dependent)", nameHe: "משוואת שרדינגר (תלוית זמן)" },
      { formula: "Ĥψ = Eψ", nameEn: "Schrödinger equation (time-independent)", nameHe: "משוואת שרדינגר (בלתי תלוית זמן)" },
      { formula: "Ĥ = p̂²/2m + V(x̂)", nameEn: "Hamiltonian operator", nameHe: "אופרטור המילטוניאן" },
      { formula: "p̂ = -iℏ ∂/∂x", nameEn: "Momentum operator", nameHe: "אופרטור התנע" },
      { formula: "Δx·Δp ≥ ℏ/2", nameEn: "Uncertainty (position-momentum)", nameHe: "אי-ודאות מקום-תנע" },
      { formula: "ΔE·Δt ≥ ℏ/2", nameEn: "Uncertainty (energy-time)", nameHe: "אי-ודאות אנרגיה-זמן" },
      { formula: "[x̂, p̂] = iℏ", nameEn: "Canonical commutator", nameHe: "יחס חילוף קנוני" },
      { formula: "P = |ψ|²", nameEn: "Born rule", nameHe: "כלל בורן" },
      { formula: "⟨A⟩ = ⟨ψ|Â|ψ⟩", nameEn: "Expectation value", nameHe: "ערך תצפית" },
      { formula: "|ψ(t)⟩ = e^(-iĤt/ℏ)|ψ(0)⟩", nameEn: "Time evolution", nameHe: "התפתחות בזמן" },
      { formula: "Eₙ = (n + ½)ℏω", nameEn: "Harmonic oscillator levels", nameHe: "רמות המתנד ההרמוני" },
      { formula: "ψₙ(x) = √(2/L) sin(nπx/L)", nameEn: "Infinite well eigenstates", nameHe: "מצבים עצמיים בבור אינסופי" },
      { formula: "Eₙ = n²π²ℏ²/2mL²", nameEn: "Infinite well energies", nameHe: "רמות אנרגיה בבור אינסופי" },
      { formula: "Eₙ = -13.6 eV/n²", nameEn: "Hydrogen energy levels", nameHe: "רמות אנרגיה במימן" },
      { formula: "T ≈ e^(-2κL),  κ = √(2m(V₀-E))/ℏ", nameEn: "Quantum tunneling", nameHe: "מנהור קוונטי" },
      { formula: "|ψ⟩ = α|0⟩ + β|1⟩", nameEn: "Qubit superposition", nameHe: "סופרפוזיציה של קיוביט" },
      { formula: "|Φ⁺⟩ = (|00⟩+|11⟩)/√2", nameEn: "Bell state", nameHe: "מצב בל" },
      { formula: "S = E(a,b) - E(a,b′) + E(a′,b) + E(a′,b′)", nameEn: "CHSH correlator", nameHe: "מתאם CHSH" },
      { formula: "|S|_classical ≤ 2,  |S|_QM ≤ 2√2", nameEn: "Bell / Tsirelson bounds", nameHe: "חסמי בל וצירלסון" },
      { formula: "A_w = ⟨φ|Â|ψ⟩ / ⟨φ|ψ⟩", nameEn: "Weak value (Aharonov)", nameHe: "ערך חלש (אהרונוב)" },
      { formula: "ρ = |ψ⟩⟨ψ|", nameEn: "Density matrix (pure state)", nameHe: "מטריצת צפיפות (מצב טהור)" },
      { formula: "ρ = Σ pᵢ|ψᵢ⟩⟨ψᵢ|", nameEn: "Density matrix (mixed state)", nameHe: "מטריצת צפיפות (מצב מעורב)" },
      { formula: "S = -Tr(ρ ln ρ)", nameEn: "von Neumann entropy", nameHe: "אנטרופיית פון נוימן" },
      { formula: "Ŝ_z|↑⟩ = (ℏ/2)|↑⟩", nameEn: "Spin-½ eigenvalue", nameHe: "ערך עצמי של ספין ½" },
      { formula: "⟨x|p⟩ = e^(ipx/ℏ)/√(2πℏ)", nameEn: "Position-momentum overlap", nameHe: "חפיפת מקום-תנע" },
    ],
  },
  {
    key: "relativity",
    labelEn: "Relativity",
    labelHe: "תורת היחסות",
    equations: [
      { formula: "E = mc²", nameEn: "Mass-energy equivalence", nameHe: "שקילות מסה-אנרגיה" },
      { formula: "E² = (pc)² + (mc²)²", nameEn: "Energy-momentum relation", nameHe: "יחס אנרגיה-תנע" },
      { formula: "E = pc", nameEn: "Photon energy-momentum", nameHe: "אנרגיה-תנע של פוטון" },
      { formula: "γ = 1/√(1-v²/c²)", nameEn: "Lorentz factor", nameHe: "פקטור לורנץ" },
      { formula: "E = γmc²", nameEn: "Relativistic energy", nameHe: "אנרגיה יחסותית" },
      { formula: "p = γmv", nameEn: "Relativistic momentum", nameHe: "תנע יחסותי" },
      { formula: "Δt′ = γΔt", nameEn: "Time dilation", nameHe: "התארכות הזמן" },
      { formula: "L′ = L/γ", nameEn: "Length contraction", nameHe: "התקצרות האורך" },
      { formula: "x′ = γ(x - vt),  t′ = γ(t - vx/c²)", nameEn: "Lorentz transformation", nameHe: "טרנספורמציית לורנץ" },
      { formula: "u′ = (u - v)/(1 - uv/c²)", nameEn: "Velocity addition", nameHe: "חיבור מהירויות" },
      { formula: "ds² = -c²dt² + dx² + dy² + dz²", nameEn: "Minkowski interval", nameHe: "אינטרוול מינקובסקי" },
      { formula: "Gμν = (8πG/c⁴)Tμν", nameEn: "Einstein field equations", nameHe: "משוואות השדה של איינשטיין" },
    ],
  },
  {
    key: "thermo",
    labelEn: "Thermodynamics & Statistical",
    labelHe: "תרמודינמיקה וסטטיסטית",
    equations: [
      { formula: "S = k ln W", nameEn: "Boltzmann entropy", nameHe: "אנטרופיית בולצמן" },
      { formula: "S = -k Σ pᵢ ln pᵢ", nameEn: "Gibbs entropy", nameHe: "אנטרופיית גיבס" },
      { formula: "dU = TdS - PdV", nameEn: "Fundamental relation", nameHe: "היחס היסודי" },
      { formula: "ΔS_universe ≥ 0", nameEn: "Second law", nameHe: "החוק השני" },
      { formula: "PV = nRT", nameEn: "Ideal gas law", nameHe: "חוק הגזים האידיאליים" },
      { formula: "⟨E⟩ = (3/2)kT", nameEn: "Equipartition (monatomic)", nameHe: "חלוקת אנרגיה שווה" },
      { formula: "⟨v²⟩ = 3kT/m", nameEn: "Mean square speed", nameHe: "מהירות ריבועית ממוצעת" },
      { formula: "F = U - TS", nameEn: "Helmholtz free energy", nameHe: "אנרגיה חופשית של הלמהולץ" },
      { formula: "G = H - TS", nameEn: "Gibbs free energy", nameHe: "אנרגיה חופשית של גיבס" },
      { formula: "Z = Σ e^(-Eᵢ/kT)", nameEn: "Partition function", nameHe: "פונקציית החלוקה" },
      { formula: "η = 1 - T_c/T_h", nameEn: "Carnot efficiency", nameHe: "נצילות קרנו" },
      { formula: "Q = mcΔT", nameEn: "Heat capacity", nameHe: "חום סגולי" },
      { formula: "P = σAT⁴", nameEn: "Stefan-Boltzmann law", nameHe: "חוק סטפן-בולצמן" },
      { formula: "λ_max T = b", nameEn: "Wien's displacement law", nameHe: "חוק ההסחה של וין" },
    ],
  },
  {
    key: "waves",
    labelEn: "Waves, Optics & Fourier",
    labelHe: "גלים, אופטיקה ופורייה",
    equations: [
      { formula: "v = fλ", nameEn: "Wave speed", nameHe: "מהירות גל" },
      { formula: "y = A sin(kx - ωt)", nameEn: "Traveling wave", nameHe: "גל מתקדם" },
      { formula: "∂²y/∂t² = v² ∂²y/∂x²", nameEn: "Wave equation", nameHe: "משוואת הגלים" },
      { formula: "f′ = f(v ± v₀)/(v ∓ vₛ)", nameEn: "Doppler effect", nameHe: "אפקט דופלר" },
      { formula: "f_beat = |f₁ - f₂|", nameEn: "Beat frequency", nameHe: "תדר פעימות" },
      { formula: "λₙ = 2L/n", nameEn: "Standing wave modes", nameHe: "אופני גל עומד" },
      { formula: "n₁sinθ₁ = n₂sinθ₂", nameEn: "Snell's law", nameHe: "חוק סנל" },
      { formula: "n = c/v", nameEn: "Refractive index", nameHe: "מקדם שבירה" },
      { formula: "1/f = 1/u + 1/v", nameEn: "Thin lens equation", nameHe: "משוואת העדשה הדקה" },
      { formula: "d sinθ = mλ", nameEn: "Diffraction / double slit maxima", nameHe: "התאבכות בונה (שני סדקים)" },
      { formula: "I = I₀cos²θ", nameEn: "Malus's law", nameHe: "חוק מאלוס" },
      { formula: "f(x) = Σ [aₙcos(nωx) + bₙsin(nωx)]", nameEn: "Fourier series", nameHe: "טור פורייה" },
      { formula: "f̂(k) = ∫ f(x) e^(-ikx) dx", nameEn: "Fourier transform", nameHe: "התמרת פורייה" },
      { formula: "f(x) = (1/2π) ∫ f̂(k) e^(ikx) dk", nameEn: "Inverse Fourier transform", nameHe: "התמרת פורייה הפוכה" },
      { formula: "Δk·Δx ≥ ½", nameEn: "Bandwidth theorem", nameHe: "משפט רוחב הסרט" },
    ],
  },
  {
    key: "fluids",
    labelEn: "Fluids",
    labelHe: "זורמים",
    equations: [
      { formula: "P = P₀ + ρgh", nameEn: "Hydrostatic pressure", nameHe: "לחץ הידרוסטטי" },
      { formula: "P + ½ρv² + ρgh = const", nameEn: "Bernoulli's equation", nameHe: "משוואת ברנולי" },
      { formula: "A₁v₁ = A₂v₂", nameEn: "Continuity equation", nameHe: "משוואת הרציפות" },
      { formula: "F_b = ρVg", nameEn: "Archimedes' principle", nameHe: "עקרון ארכימדס" },
      { formula: "Re = ρvL/μ", nameEn: "Reynolds number", nameHe: "מספר ריינולדס" },
      { formula: "ρ(∂v/∂t + v·∇v) = -∇P + μ∇²v + ρg", nameEn: "Navier-Stokes equation", nameHe: "משוואת נאבייה-סטוקס" },
      { formula: "∂v/∂t + v·∇v = -∇P/ρ + ν∇²v + g", nameEn: "Navier-Stokes (kinematic form)", nameHe: "נאבייה-סטוקס (צורה קינמטית)" },
      { formula: "∇·v = 0", nameEn: "Incompressible continuity", nameHe: "רציפות בזורם בלתי-דחיס" },
      { formula: "F_d = 6πμrv", nameEn: "Stokes' drag", nameHe: "כוח גרר של סטוקס" },
    ],
  },
  {
    key: "nuclear",
    labelEn: "Nuclear",
    labelHe: "גרעין",
    equations: [
      { formula: "N(t) = N₀e^(-λt)", nameEn: "Radioactive decay", nameHe: "דעיכה רדיואקטיבית" },
      { formula: "t₁⸝₂ = ln2/λ", nameEn: "Half-life", nameHe: "זמן מחצית החיים" },
      { formula: "A = λN", nameEn: "Activity", nameHe: "פעילות" },
      { formula: "E_bind = Δm·c²", nameEn: "Binding energy", nameHe: "אנרגיית קשר" },
    ],
  },
  {
    key: "math",
    labelEn: "Mathematics",
    labelHe: "מתמטיקה",
    equations: [
      { formula: "e^(iπ) + 1 = 0", nameEn: "Euler's identity", nameHe: "זהות אוילר" },
      { formula: "e^(iθ) = cosθ + i sinθ", nameEn: "Euler's formula", nameHe: "נוסחת אוילר" },
      { formula: "a² + b² = c²", nameEn: "Pythagorean theorem", nameHe: "משפט פיתגורס" },
      { formula: "x = (-b ± √(b²-4ac))/2a", nameEn: "Quadratic formula", nameHe: "נוסחת השורשים" },
      { formula: "f(x) = Σ f⁽ⁿ⁾(a)(x-a)ⁿ/n!", nameEn: "Taylor series", nameHe: "טור טיילור" },
      { formula: "∫₋∞^∞ e^(-x²) dx = √π", nameEn: "Gaussian integral", nameHe: "אינטגרל גאוסי" },
      { formula: "n! ≈ √(2πn)(n/e)ⁿ", nameEn: "Stirling's approximation", nameHe: "קירוב סטירלינג" },
      { formula: "(a+b)ⁿ = Σ C(n,k) aᵏbⁿ⁻ᵏ", nameEn: "Binomial theorem", nameHe: "הבינום של ניוטון" },
      { formula: "e = lim (1 + 1/n)ⁿ", nameEn: "Definition of e", nameHe: "הגדרת e" },
      { formula: "∫ₐᵇ f′(x)dx = f(b) - f(a)", nameEn: "Fundamental theorem of calculus", nameHe: "המשפט היסודי של החשבון" },
      { formula: "∮ F·dl = ∫(∇×F)·dA", nameEn: "Stokes' theorem", nameHe: "משפט סטוקס" },
      { formula: "∫ ∇·F dV = ∮ F·dA", nameEn: "Divergence theorem", nameHe: "משפט הדיברגנץ" },
      { formula: "∇²φ = 0", nameEn: "Laplace equation", nameHe: "משוואת לפלס" },
      { formula: "∫ f(x)δ(x-a)dx = f(a)", nameEn: "Dirac delta", nameHe: "דלתא של דיראק" },
      { formula: "ζ(s) = Σ 1/nˢ", nameEn: "Riemann zeta function", nameHe: "פונקציית זטא של רימן" },
      { formula: "d/dx eˣ = eˣ", nameEn: "Exponential derivative", nameHe: "נגזרת האקספוננט" },
    ],
  },
];

export const TOTAL_EQUATIONS = EQUATION_CATEGORIES.reduce(
  (sum, cat) => sum + cat.equations.length,
  0
);

// ── "By physicist" view ────────────────────────────────────────────────────
// A second lens on the same equations, grouped by the person behind them.
// Single source of truth: equations stay in EQUATION_CATEGORIES; here we only
// attribute them (an equation may belong to more than one physicist).

export interface Physicist {
  key: string;
  nameEn: string;
  nameHe: string;
}

// Display order of the "By physicist" groups.
export const PHYSICISTS: Physicist[] = [
  { key: "newton", nameEn: "Isaac Newton", nameHe: "אייזק ניוטון" },
  { key: "euler", nameEn: "Leonhard Euler", nameHe: "לאונרד אוילר" },
  { key: "lagrange", nameEn: "Joseph-Louis Lagrange", nameHe: "ז'וזף-לואי לגראנז'" },
  { key: "dalembert", nameEn: "Jean d'Alembert", nameHe: "ז'אן ד'אלמבר" },
  { key: "hamilton", nameEn: "William Rowan Hamilton", nameHe: "ויליאם רואן המילטון" },
  { key: "poisson", nameEn: "Siméon Poisson", nameHe: "סימאון פואסון" },
  { key: "liouville", nameEn: "Joseph Liouville", nameHe: "ז'וזף ליוביל" },
  { key: "noether", nameEn: "Emmy Noether", nameHe: "אמי נתר" },
  { key: "hooke", nameEn: "Robert Hooke", nameHe: "רוברט הוק" },
  { key: "kepler", nameEn: "Johannes Kepler", nameHe: "יוהאנס קפלר" },
  { key: "coulomb", nameEn: "Charles-Augustin de Coulomb", nameHe: "שארל-אוגוסטן דה קולון" },
  { key: "gauss", nameEn: "Carl Friedrich Gauss", nameHe: "קרל פרידריך גאוס" },
  { key: "faraday", nameEn: "Michael Faraday", nameHe: "מייקל פאראדיי" },
  { key: "ampere", nameEn: "André-Marie Ampère", nameHe: "אנדרה-מארי אמפר" },
  { key: "ohm", nameEn: "Georg Ohm", nameHe: "גאורג אוהם" },
  { key: "maxwell", nameEn: "James Clerk Maxwell", nameHe: "ג'יימס קלרק מקסוול" },
  { key: "lorentz", nameEn: "Hendrik Lorentz", nameHe: "הנדריק לורנץ" },
  { key: "einstein", nameEn: "Albert Einstein", nameHe: "אלברט איינשטיין" },
  { key: "minkowski", nameEn: "Hermann Minkowski", nameHe: "הרמן מינקובסקי" },
  { key: "planck", nameEn: "Max Planck", nameHe: "מקס פלאנק" },
  { key: "bohr", nameEn: "Niels Bohr", nameHe: "נילס בוהר" },
  { key: "debroglie", nameEn: "Louis de Broglie", nameHe: "לואי דה-ברויי" },
  { key: "compton", nameEn: "Arthur Compton", nameHe: "ארתור קומפטון" },
  { key: "rydberg", nameEn: "Johannes Rydberg", nameHe: "יוהאנס רידברג" },
  { key: "schrodinger", nameEn: "Erwin Schrödinger", nameHe: "ארווין שרדינגר" },
  { key: "heisenberg", nameEn: "Werner Heisenberg", nameHe: "ורנר הייזנברג" },
  { key: "dirac", nameEn: "Paul Dirac", nameHe: "פול דיראק" },
  { key: "born", nameEn: "Max Born", nameHe: "מקס בורן" },
  { key: "vonneumann", nameEn: "John von Neumann", nameHe: "ג'ון פון נוימן" },
  { key: "bell", nameEn: "John Stewart Bell", nameHe: "ג'ון סטיוארט בל" },
  { key: "aharonov", nameEn: "Yakir Aharonov", nameHe: "יקיר אהרונוב" },
  { key: "boltzmann", nameEn: "Ludwig Boltzmann", nameHe: "לודוויג בולצמן" },
  { key: "gibbs", nameEn: "Josiah Willard Gibbs", nameHe: "ג'וזיה וילארד גיבס" },
  { key: "carnot", nameEn: "Sadi Carnot", nameHe: "סאדי קרנו" },
  { key: "wien", nameEn: "Wilhelm Wien", nameHe: "וילהלם וין" },
  { key: "fourier", nameEn: "Joseph Fourier", nameHe: "ז'וזף פורייה" },
  { key: "doppler", nameEn: "Christian Doppler", nameHe: "כריסטיאן דופלר" },
  { key: "snell", nameEn: "Willebrord Snell", nameHe: "וילברורד סנל" },
  { key: "malus", nameEn: "Étienne-Louis Malus", nameHe: "אטיין-לואי מאלוס" },
  { key: "bernoulli", nameEn: "Daniel Bernoulli", nameHe: "דניאל ברנולי" },
  { key: "navierstokes", nameEn: "Navier & Stokes", nameHe: "נאבייה וסטוקס" },
  { key: "reynolds", nameEn: "Osborne Reynolds", nameHe: "אוסבורן ריינולדס" },
  { key: "archimedes", nameEn: "Archimedes", nameHe: "ארכימדס" },
  { key: "hubble", nameEn: "Edwin Hubble", nameHe: "אדווין האבל" },
  { key: "friedmann", nameEn: "Alexander Friedmann", nameHe: "אלכסנדר פרידמן" },
  { key: "schwarzschild", nameEn: "Karl Schwarzschild", nameHe: "קרל שוורצשילד" },
  { key: "hawking", nameEn: "Bekenstein & Hawking", nameHe: "בקנשטיין והוקינג" },
  { key: "pythagoras", nameEn: "Pythagoras", nameHe: "פיתגורס" },
  { key: "riemann", nameEn: "Bernhard Riemann", nameHe: "ברנהרד רימן" },
  { key: "laplace", nameEn: "Pierre-Simon Laplace", nameHe: "פייר-סימון לפלס" },
  { key: "stirling", nameEn: "James Stirling", nameHe: "ג'יימס סטירלינג" },
  { key: "taylor", nameEn: "Brook Taylor", nameHe: "ברוק טיילור" },
];

// Equation (by English name) → physicist key(s). Multiple keys = appears under
// each of them (e.g. Gauss's law under Maxwell AND Gauss).
const PHYSICIST_BY_NAME: Record<string, string[]> = {
  "Newton's second law": ["newton"],
  "Newton's second law (momentum)": ["newton"],
  "Newton's gravitation": ["newton"],
  "Binomial theorem": ["newton"],
  "Lagrangian": ["lagrange"],
  "Euler-Lagrange equations": ["euler", "lagrange"],
  "Euler-Lagrange (generalized forces)": ["euler", "lagrange"],
  "Lagrange multipliers (constraints)": ["lagrange"],
  "Euler's identity": ["euler"],
  "Euler's formula": ["euler"],
  "D'Alembert's principle": ["dalembert"],
  "Hamiltonian (Legendre transform)": ["hamilton"],
  "Hamilton's equation (position)": ["hamilton"],
  "Hamilton's equation (momentum)": ["hamilton"],
  "Hamilton's principle (stationary action)": ["hamilton"],
  "Hamilton-Jacobi equation": ["hamilton"],
  "Hamilton's characteristic function": ["hamilton"],
  "Poisson bracket": ["poisson"],
  "Fundamental Poisson brackets": ["poisson"],
  "Evolution via Poisson bracket": ["poisson"],
  "Liouville's equation": ["liouville"],
  "Liouville's theorem": ["liouville"],
  "Noether charge (conserved)": ["noether"],
  "Hooke's law": ["hooke"],
  "Kepler's third law": ["kepler"],
  "Coulomb's law": ["coulomb"],
  "Gauss's law (Maxwell I)": ["maxwell", "gauss"],
  "No magnetic monopoles (Maxwell II)": ["maxwell"],
  "Faraday's law (Maxwell III)": ["maxwell", "faraday"],
  "Ampère-Maxwell law (Maxwell IV)": ["maxwell", "ampere"],
  "Induced EMF": ["faraday"],
  "Ohm's law": ["ohm"],
  "Divergence theorem": ["gauss"],
  "Gaussian integral": ["gauss"],
  "Lorentz force": ["lorentz"],
  "Lorentz factor": ["lorentz"],
  "Lorentz transformation": ["lorentz"],
  "Mass-energy equivalence": ["einstein"],
  "Energy-momentum relation": ["einstein"],
  "Relativistic energy": ["einstein"],
  "Relativistic momentum": ["einstein"],
  "Time dilation": ["einstein"],
  "Length contraction": ["einstein"],
  "Einstein field equations": ["einstein"],
  "Photoelectric effect": ["einstein"],
  "Photoelectron kinetic energy": ["einstein"],
  "Photoelectron energy (ℏω form)": ["einstein"],
  "Minkowski interval": ["minkowski"],
  "Planck relation": ["planck"],
  "Hydrogen energy levels": ["bohr"],
  "de Broglie wavelength": ["debroglie"],
  "Compton scattering": ["compton"],
  "Rydberg formula": ["rydberg"],
  "Schrödinger equation (time-dependent)": ["schrodinger"],
  "Schrödinger equation (time-independent)": ["schrodinger"],
  "Uncertainty (position-momentum)": ["heisenberg"],
  "Uncertainty (energy-time)": ["heisenberg"],
  "Dirac delta": ["dirac"],
  "Expectation value": ["dirac"],
  "Qubit superposition": ["dirac"],
  "Density matrix (pure state)": ["dirac", "vonneumann"],
  "Density matrix (mixed state)": ["dirac", "vonneumann"],
  "Born rule": ["born"],
  "von Neumann entropy": ["vonneumann"],
  "Bell state": ["bell"],
  "CHSH correlator": ["bell"],
  "Bell / Tsirelson bounds": ["bell"],
  "Weak value (Aharonov)": ["aharonov"],
  "Boltzmann entropy": ["boltzmann"],
  "Stefan-Boltzmann law": ["boltzmann"],
  "Gibbs entropy": ["gibbs"],
  "Gibbs free energy": ["gibbs"],
  "Carnot efficiency": ["carnot"],
  "Wien's displacement law": ["wien"],
  "Fourier series": ["fourier"],
  "Fourier transform": ["fourier"],
  "Inverse Fourier transform": ["fourier"],
  "Doppler effect": ["doppler"],
  "Snell's law": ["snell"],
  "Malus's law": ["malus"],
  "Bernoulli's equation": ["bernoulli"],
  "Navier-Stokes equation": ["navierstokes"],
  "Navier-Stokes (kinematic form)": ["navierstokes"],
  "Stokes' drag": ["navierstokes"],
  "Stokes' theorem": ["navierstokes"],
  "Reynolds number": ["reynolds"],
  "Archimedes' principle": ["archimedes"],
  "Hubble's law": ["hubble"],
  "Friedmann equation": ["friedmann"],
  "Schwarzschild radius": ["schwarzschild"],
  "Bekenstein-Hawking entropy": ["hawking"],
  "Pythagorean theorem": ["pythagoras"],
  "Riemann zeta function": ["riemann"],
  "Laplace equation": ["laplace"],
  "Stirling's approximation": ["stirling"],
  "Taylor series": ["taylor"],
};

const ALL_EQUATIONS = EQUATION_CATEGORIES.flatMap((c) => c.equations);

// Same shape as EQUATION_CATEGORIES so the modal can render either the same way.
export const PHYSICIST_CATEGORIES: EquationCategory[] = PHYSICISTS.map((p) => ({
  key: p.key,
  labelEn: p.nameEn,
  labelHe: p.nameHe,
  equations: ALL_EQUATIONS.filter((e) =>
    (PHYSICIST_BY_NAME[e.nameEn] || []).includes(p.key)
  ),
})).filter((c) => c.equations.length > 0);
